name: okdio_generator
description: okdio is an dio client generator using source_gen and inspired from retrofit based on chopper
version: 0.0.2
homepage: https://github.com/mitty1987/based_on_chopper
author: Private <cjasq1@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  analyzer: ^0.39.4
  build: ^1.2.2
  logging: ^0.11.0
  source_gen: ^0.9.4+7
  okdio: ^0.0.3
  code_builder: ^3.2.1
  dart_style: ^1.3.3
  built_collection: ^4.3.2

#dependency_overrides:
#  okdio:
#    path: ../okdio