name: okdio_generator
description: okdio is an dio client generator using source_gen and inspired from retrofit based on chopper
version: 0.0.1
homepage: https://github.com/mitty1987/based_on_chopper
author: Private <cjasq1@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.2
  analyzer: ^0.34.0
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  okdio:
    path: ../okdio
  code_builder: ^3.0.0
  dart_style: ^1.0.10
  built_collection: ^3.1.3

dev_dependencies:
  test: ^1.3.0

dependency_overrides:
  okdio:
    path: ../okdio