name: okdio
description: okdio is an dio client generator using source_gen and inspired from retrofit based on chopper
version: 0.0.1
homepage: https://github.com/mitty1987/based_on_chopper
author: Private <cjasq1@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dio: ^2.0.7
  meta: ^1.1.2
  rxdart: ^0.21.0
  logging: ^0.11.3
  dson: ^0.15.5

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.0.0
  #build_test:
  coverage: ^0.12.2
  build_web_compilers: any