name: okdio
description: okdio is an dio client generator using source_gen and inspired from retrofit based on chopper
version: 0.0.3
homepage: https://github.com/mitty1987/based_on_chopper

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  dio: ^3.0.8
  meta: ^1.1.8
  rxdart: ^0.23.1
  logging: ^0.11.3
  dson: ^0.16.0

dev_dependencies:
  test: ^1.12.0
  build_runner: ^1.7.4
  #build_test:
  coverage: ^0.13.5
  build_web_compilers: any
#  okdio_generator:
#    path: ../okdio_generator